### ISSUE TITLE
Use Hypothesis tests

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/Ciw#11]
(moving @drvinceknight 's issue from ASQ)

**Comment by sluenenglish** [comment]
Started on clean-init branch

**Comment by drvinceknight** [comment]
Keep an eye out for next Hypothesis release which will have a better way of handling random stuff: https://github.com/DRMacIver/hypothesis/commit/f0919fdae5e912e6b388631bf3f89cbcea6284c3

**Comment by geraintpalmer** [comment]
This is ongoing so am going to close the issue, happy @drvinceknight? :hatching_chick:

**Comment by drvinceknight** [comment]
:+1:
