### ISSUE TITLE
Priority Queues

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/Ciw#12]
Each class can have priority associated with it.

Essentially a separate queue for each priority level at each service centre

**Comment by wibrt** [comment]
This would be a nice feature

**Comment by geraintpalmer** [comment]
Hi @wibrt we're currently having a bit of a refactor (see #45), but hopefully can get to this sooner rather than later 🐣

**Comment by drvinceknight** [comment]
@geraintpalmer I know we're basically there with the `priority` branch but as well as the test we discussed I think the other thing that needs to be added in before it is merged is docs for it (nothing too complex is needed).

**Comment by geraintpalmer** [comment]
Implemented in commit 2f9b77f8601a4001bbdfd616ab57ececaf7b7f1e

**Comment by wibrt** [comment]
nice
