### ISSUE TITLE
Get pip to install requirements also

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/Ciw#14]

**Comment by geraintpalmer** [comment]
I think commit be8c66c05d69684212909dabfe81daf6946a6a76 does it, but need to test when pip installing first.

**Comment by geraintpalmer** [comment]
Didn't fix it...

**Comment by drvinceknight** [comment]
Listening in (I want this in Axelrod so no sure what is wrong: take a look at other libraries around?).

**Comment by geraintpalmer** [comment]
Fixed with commit 41c9b19c9ea871bc6de8e58c012bb3d3ec54ee46
