### ISSUE TITLE
Custom probability functions for service/interarrival times

### ISSUE THREAD

**Issue by sluenenglish** [geraintpalmer/Ciw#30]
Option to pass Ciw a function to sample from to obtain service / inter-arrival times

**Comment by geraintpalmer** [comment]
@sluenenglish you happy to do this?

**Comment by sluenenglish** [comment]
Yes sure :+1:  will give it a go

**Comment by geraintpalmer** [comment]
:boom: :hatching_chick: :rooster: :toilet: :basketball: :art: :bento: :rocket:

**Comment by geraintpalmer** [comment]
Implemented with commit 012c60bb3cee688aa4496a62306ecea84c9673b4 :hatching_chick:
