### ISSUE TITLE
Modularise Deadlock Detection

### ISSUE THREAD

**Issue by geraintpalmer** [geraintpalmer/Ciw#41]
Therefore can recreate other deadlock detection methods, and compare.

**Comment by drvinceknight** [comment]
This is a good idea. My suggestion would be something like a general Deadlock class and then inheriting from that as necessary overwriting specific methods.

**Comment by geraintpalmer** [comment]
Thanks Vince. Yeah I'm thinking something similar to what I did with the
StateTracker class, an overall class that just 'passes' all the time (no
detection), then others that inherit from there. Hopefully then do
something similar with deadlock resolution eventually.

**Comment by drvinceknight** [comment]
That sounds good to me.

**Comment by geraintpalmer** [comment]
Initially implemented with commit 95ac4c5082c21f104fdaf9b7413659b68c0cb741

**Comment by geraintpalmer** [comment]
Now to implement a new deadlock detection scheme: recreate that described in https://scholar.google.co.uk/scholar?cluster=794316054931344023&hl=en&as_sdt=0,5

**Comment by geraintpalmer** [comment]
Implemented with commit e92d678f3ab916153c5f04adec22a30a54b22bac
