### ISSUE TITLE
Doctest the docs.

### ISSUE THREAD

**Issue by drvinceknight** [geraintpalmer/Ciw#7]

**Comment by drvinceknight** [comment]
Use this (runs doctests as unitests: works better with travis): https://github.com/Axelrod-Python/Axelrod/blob/master/doctests.py

**Comment by geraintpalmer** [comment]
Hi @drvinceknight could you work with me started getting the docs both tested and readable please?

**Comment by drvinceknight** [comment]
Rocket process 🚀

**Comment by geraintpalmer** [comment]
I think this does it commit 09b7e304aafc828195abcae089fcd466e91f24c0

Although this doesn't run doctests.py when running unittests, is it supposed to?

**Comment by drvinceknight** [comment]
> Although this doesn't run doctests.py when running unittests, is it supposed to?

Nope it's not supposed to. 

Unitests is just a python module, so when you run `python -m discover....` it uses that library.

To run the doctests you need to specifically run that python file. I've sent you https://github.com/geraintpalmer/Ciw/pull/25 which does it on travis.

**Comment by drvinceknight** [comment]
You could if you wanted to: have a file that ran both test commands so you could just type:

```
./test.sh
```

and run both the tests (unit and doc).

**Comment by drvinceknight** [comment]
:rocket: :shipit:

**Comment by geraintpalmer** [comment]
Fixed with commit 6951d39ae011ee694bf2fd2c7bb2bbc66a946de0
